// Datos de prueba para desarrollo. [pregunta, opciones, índice correcto, dificultad]
export type SeedQuestion = [string, string[], number, number];

export const seedCategories: { slug: string; name: string; icon: string; description: string; questions: SeedQuestion[] }[] = [
  {
    slug: "futbol",
    name: "Fútbol",
    icon: "⚽",
    description: "Mundiales, clubes, ídolos y récords.",
    questions: [
      ["¿Qué selección ganó el Mundial de Qatar 2022?", ["Francia", "Argentina", "Brasil", "Croacia"], 1, 1],
      ["¿Cuántos jugadores tiene un equipo de fútbol en cancha?", ["10", "11", "12", "9"], 1, 1],
      ["¿En qué año se jugó el primer Mundial?", ["1926", "1930", "1934", "1950", "1928"], 1, 2],
      ["¿Qué país ganó más Copas del Mundo?", ["Alemania", "Italia", "Brasil", "Argentina"], 2, 1],
      ["¿Qué club es conocido como 'El Xeneize'?", ["River Plate", "Boca Juniors", "Racing", "Independiente"], 1, 1],
      ["¿Quién es el máximo goleador histórico de los Mundiales?", ["Pelé", "Ronaldo Nazário", "Miroslav Klose", "Lionel Messi"], 2, 3],
      ["¿Qué país organizó el Mundial 1978?", ["México", "Argentina", "España", "Uruguay"], 1, 2],
      ["¿Cuánto dura un partido reglamentario sin descuento?", ["80 minutos", "90 minutos", "100 minutos", "120 minutos"], 1, 1],
      ["¿Qué club ganó más Copas Libertadores?", ["Boca Juniors", "Peñarol", "Independiente", "River Plate"], 2, 3],
      ["¿En qué país se juega la Premier League?", ["España", "Inglaterra", "Italia", "Alemania"], 1, 1],
      ["¿Qué jugador ganó más Balones de Oro?", ["Cristiano Ronaldo", "Lionel Messi", "Michel Platini", "Johan Cruyff"], 1, 2],
      ["¿De qué color es la tarjeta de expulsión?", ["Amarilla", "Roja", "Verde", "Azul"], 1, 1],
    ],
  },
  {
    slug: "cine",
    name: "Cine",
    icon: "🎬",
    description: "Películas, directores, actores y premios.",
    questions: [
      ["¿Quién dirigió 'El Padrino'?", ["Martin Scorsese", "Francis Ford Coppola", "Steven Spielberg", "Brian De Palma"], 1, 2],
      ["¿Qué película argentina ganó el Oscar en 2010?", ["Relatos salvajes", "El secreto de sus ojos", "Nueve reinas", "La historia oficial"], 1, 2],
      ["¿En qué película aparece el personaje Forrest Gump?", ["Big", "Forrest Gump", "Náufrago", "Philadelphia"], 1, 1],
      ["¿Cómo se llama el mago protagonista de la saga de J. K. Rowling?", ["Frodo", "Harry Potter", "Merlín", "Gandalf"], 1, 1],
      ["¿Qué estudio creó 'Toy Story'?", ["DreamWorks", "Pixar", "Illumination", "Blue Sky"], 1, 1],
      ["¿Quién interpretó a Jack en 'Titanic'?", ["Brad Pitt", "Leonardo DiCaprio", "Matt Damon", "Johnny Depp"], 1, 1],
      ["¿Cuál es la película más taquillera de la historia (sin ajustar inflación)?", ["Titanic", "Avatar", "Avengers: Endgame", "Star Wars: El despertar de la Fuerza"], 1, 3],
      ["¿Qué director hizo 'Pulp Fiction'?", ["Quentin Tarantino", "Guy Ritchie", "David Fincher", "Christopher Nolan"], 0, 2],
      ["¿En qué año se estrenó 'Jurassic Park'?", ["1990", "1993", "1995", "1997"], 1, 2],
      ["¿Qué actor dio vida a Neo en 'Matrix'?", ["Keanu Reeves", "Tom Cruise", "Will Smith", "Hugh Jackman"], 0, 1],
      ["¿Cómo se llama el premio principal del Festival de Cannes?", ["León de Oro", "Palma de Oro", "Oso de Oro", "Concha de Oro"], 1, 3],
    ],
  },
  {
    slug: "series",
    name: "Series",
    icon: "📺",
    description: "Las series que todos vimos (y las que no).",
    questions: [
      ["¿En qué ciudad transcurre 'Breaking Bad'?", ["Phoenix", "Albuquerque", "El Paso", "Las Vegas"], 1, 2],
      ["¿Cómo se llama la cafetería de 'Friends'?", ["Central Perk", "Monk's", "MacLaren's", "Luke's"], 0, 1],
      ["¿Qué casa tiene como lema 'Se acerca el invierno'?", ["Lannister", "Stark", "Targaryen", "Baratheon"], 1, 1],
      ["¿Qué serie tiene como protagonista a Walter White?", ["Ozark", "Breaking Bad", "Better Call Saul", "Narcos"], 1, 1],
      ["¿En qué país se ambienta 'La casa de papel'?", ["México", "España", "Argentina", "Colombia"], 1, 1],
      ["¿Cómo se llama el mundo paralelo de 'Stranger Things'?", ["El Otro Lado", "El Mundo del Revés", "La Zona Oscura", "El Abismo"], 1, 2],
      ["¿Qué plataforma produjo 'The Crown'?", ["HBO", "Netflix", "Amazon", "Disney+"], 1, 2],
      ["¿Cuántas temporadas tiene 'Los Simpson'? (aprox. a 2025)", ["Menos de 20", "Entre 20 y 30", "Más de 35", "Exactamente 30"], 2, 3],
      ["¿En qué serie argentina trabajan Santos, Medina, Ravenna y Lamponne?", ["Okupas", "Los simuladores", "Epitafios", "Tumberos"], 1, 2],
      ["¿Cómo se llama el protagonista de 'Dr. House'?", ["Gregory House", "James Wilson", "Eric Foreman", "Robert Chase"], 0, 1],
    ],
  },
  {
    slug: "paises",
    name: "Países",
    icon: "🌎",
    description: "Capitales, banderas y geografía del mundo.",
    questions: [
      ["¿Cuál es la capital de Australia?", ["Sídney", "Melbourne", "Canberra", "Perth"], 2, 2],
      ["¿Cuál es el país más grande del mundo por superficie?", ["Canadá", "China", "Rusia", "Estados Unidos"], 2, 1],
      ["¿Cuál es la capital de Canadá?", ["Toronto", "Ottawa", "Vancouver", "Montreal"], 1, 2],
      ["¿Qué país tiene forma de bota?", ["Grecia", "Italia", "Portugal", "Croacia"], 1, 1],
      ["¿Cuál es el río más largo de Sudamérica?", ["Paraná", "Amazonas", "Orinoco", "Magdalena"], 1, 1],
      ["¿En qué continente está Egipto?", ["Asia", "África", "Europa", "Oceanía"], 1, 1],
      ["¿Cuál es la capital de Bolivia (sede de gobierno)?", ["Sucre", "La Paz", "Cochabamba", "Santa Cruz"], 1, 3],
      ["¿Qué país tiene más habitantes (2024)?", ["China", "India", "Estados Unidos", "Indonesia"], 1, 2],
      ["¿Cuál es la montaña más alta de América?", ["Chimborazo", "Aconcagua", "Denali", "Ojos del Salado"], 1, 2],
      ["¿Cuál es la capital de Japón?", ["Kioto", "Osaka", "Tokio", "Hiroshima"], 2, 1],
      ["¿Cuántas provincias tiene Argentina (sin contar CABA)?", ["22", "23", "24", "25"], 1, 2],
      ["¿Qué país limita con Argentina, Bolivia y Brasil a la vez?", ["Chile", "Paraguay", "Uruguay", "Perú"], 1, 2],
    ],
  },
  {
    slug: "musica",
    name: "Música",
    icon: "🎵",
    description: "Rock, pop, folklore y todo lo que suena.",
    questions: [
      ["¿Qué banda grabó el álbum 'Abbey Road'?", ["The Rolling Stones", "The Beatles", "Queen", "Pink Floyd"], 1, 1],
      ["¿Quién era el cantante de Soda Stereo?", ["Charly García", "Gustavo Cerati", "Fito Páez", "Andrés Calamaro"], 1, 1],
      ["¿Cuántas cuerdas tiene una guitarra clásica?", ["4", "5", "6", "7"], 2, 1],
      ["¿De qué país es la banda ABBA?", ["Noruega", "Suecia", "Dinamarca", "Finlandia"], 1, 2],
      ["¿Quién compuso 'Las cuatro estaciones'?", ["Mozart", "Vivaldi", "Bach", "Beethoven"], 1, 2],
      ["¿Cuál es el verdadero nombre de Freddie Mercury?", ["Farrokh Bulsara", "Frederick Mercer", "Fred Bulsar", "Farid Mercuri"], 0, 3],
      ["¿Qué instrumento tocaba principalmente Astor Piazzolla?", ["Piano", "Bandoneón", "Violín", "Guitarra"], 1, 1],
      ["¿Qué cantante es conocida como 'la Reina del Pop'?", ["Beyoncé", "Madonna", "Lady Gaga", "Britney Spears"], 1, 1],
      ["¿Cuántas notas musicales hay en la escala diatónica?", ["5", "7", "8", "12"], 1, 2],
      ["¿Qué banda argentina grabó 'Artaud'?", ["Sui Generis", "Pescado Rabioso", "Almendra", "Serú Girán"], 1, 3],
    ],
  },
];
